### ISSUE TITLE
Sort out render workflow

### ISSUE THREAD

**Issue by pat-alt** [pat-alt/julia-deeplearning-book#10]
Started working on a 'render on push' workflow, but the `build IJulia` step is still missing. 

This [blog post](https://forem.julialang.org/kellertuer/render-quarto-tutorials-in-documenterjl-with-github-actions-3fo) by @kellertuer is a great reference and I've lifted some of the things you find in `.github/workflows/quarto-render.yml` from there. The difference is that we don't have Documenter involved, so this should overall be easier. I'm just not sure where to place the build step.

**Comment by kellertuer** [comment]
I also just call quarto render – just with a fancy update to the environment all my quarto notebooks use, see

https://github.com/JuliaManifolds/Manopt.jl/blob/583efd26d33513205ce0fa9215d038f8ea78d6d4/docs/make.jl#L23-L28

which basically makes sure IJulia is build on the current Julia version running and that the environment is instantiated – but the quarto call could also just be a shell command in the render GitHub action.

**Comment by pat-alt** [comment]
Thanks again, Ronny! I'm still getting an error that the kernel could not be found: https://github.com/pat-alt/julia-deeplearning-book/actions/runs/5818658024/job/15775517299#step:8:756 

Any idea what's going wrong here?

**Comment by kellertuer** [comment]
That a probably means that IJulia is not built on 1.9; so when you `Pkg.build("IJulia")` it sets up the kernels it knows.
That's why my `make.jl` does have this line https://github.com/JuliaManifolds/Manopt.jl/blob/583efd26d33513205ce0fa9215d038f8ea78d6d4/docs/make.jl#L26

to make sure IJulia is build on every make run and know the right kernel.

**Comment by kellertuer** [comment]
Ahm, I see you do that already - is your Julia Cache maybe too eager and caches that (wrongly)? My Julia cache is a bit minimalistic exactly because I had similar problems when caching precompiled packages.

**Comment by pat-alt** [comment]
hmm I just removed the cache altogether and that also doesn't seem to be working. I'm probably doing something stupid somewhere else

**Comment by pat-alt** [comment]
That was it indeed, thanks! All working now 😄

**Comment by kellertuer** [comment]
Yay! 🥳
Checking your recent commits, you also had the `make-docs.jl --quarto` run call, which for me only works since my docs make script is also executable as a Julia script, and then the `--quarto` can be used to trigger quarto – and otherwise it uses the cached/prerendered versions (so I do not have to run quarto every time locally)

But besides that – great that it works now!
And sure such a setup takes a bit to figure out (took me 3 weeks), but I still love how well it works now :)
